### ISSUE TITLE
Anything news about Microsoft.UI.Xaml.dll issue?

### ISSUE THREAD

**Issue by Strypper** [mpulukkinen/MauiApp2DoesNotStart#1]

**Comment by mpulukkinen** [comment]
https://www.reddit.com/r/dotnetMAUI/comments/1gskk85/comment/lyrtmzy/?context=3
It's probably community toolkit issue. So, maybe this ticket should be closed?

**Comment by Strypper** [comment]
I remember now, what stuffs did you use in the toolkit?

**Comment by Strypper** [comment]
Yes it's community toolkit snackbar
